# Generated by Django 4.2.7 on 2023-12-04 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutri_score_weight', models.FloatField(default=0.2)),
                ('vegan_vegetarian_weight', models.FloatField(default=0.1)),
                ('palm_oil_free_weight', models.FloatField(default=0.1)),
                ('eco_score_weight', models.FloatField(default=0.2)),
                ('nova_group_weight', models.FloatField(default=0.1)),
                ('allergens_weight', models.FloatField(default=0.1)),
                ('gluten_milk_nuts_peanuts_soybeans_weight', models.FloatField(default=0.1)),
                ('additives_weight', models.FloatField(default=0.1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
