# Generated by Django 4.2.7 on 2023-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_preferences_additives_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='additives_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='eco_score_weight',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='gluten_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='milk_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='nova_group_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='nutri_score_weight',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='nuts_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='palm_oil_free_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='peanuts_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='soybeans_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='vegan_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='vegetarian_weight',
            field=models.IntegerField(default=1),
        ),
    ]
