# Generated by Django 4.2.7 on 2023-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='allergens_weight',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='gluten_milk_nuts_peanuts_soybeans_weight',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='vegan_vegetarian_weight',
        ),
        migrations.AddField(
            model_name='preferences',
            name='gluten_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='milk_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='nuts_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='peanuts_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='soybeans_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='vegan_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='vegetarian_weight',
            field=models.FloatField(default=0.1),
        ),
    ]
